logging:
  level:
    guru.springframework: debug
    org.hibernate: warn
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database-platform: org.hibernate.dialect.MariaDB105Dialect
    database: mysql
    show-sql: false
    # ENABLE BELOW TO CREATE NEW ADD AND DROP SCRIPTS
  sql:
    init:
      platform: mariadb
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: drop-and-create
#              create-target: grg_mariadb_create.sql
#              drop-target: grg_mariadb_drop.sql
