logging:
  level:
    guru.springframework: debug
    org.hibernate: warn
spring:
  datasource:
    platform: mariadb
    url: jdbc:mariadb://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database-platform: org.hibernate.dialect.MariaDB106Dialect : WON'T WORK CANNOT FIND DEFINITION
    database: mysql
    show-sql: false
    # ENABLE BELOW TO CREATE NEW ADD AND DROP SCRIPTS
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: drop-and-create
#              create-target: grg_mariadb_create.sql
#              drop-target: grg_mariadb_drop.sql
