INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('Cup');
INSERT INTO unit_of_measure (description) VALUES ('Pinch');
INSERT INTO unit_of_measure (description) VALUES ('Ounce');
INSERT INTO unit_of_measure (description) VALUES ('Each');
INSERT INTO unit_of_measure (description) VALUES ('Dash');
INSERT INTO unit_of_measure (description) VALUES ('Pint');
INSERT INTO base_ingredient (description) VALUES ('Ancho Chili Powder');
INSERT INTO base_ingredient (description) VALUES ('Arugala, baby, chopped');
INSERT INTO base_ingredient (description) VALUES ('Avacado, ripe');
INSERT INTO base_ingredient (description) VALUES ('Avacado, sliced');
INSERT INTO base_ingredient (description) VALUES ('Chicken, boneless thighs');
INSERT INTO base_ingredient (description) VALUES ('Cilantro, roughly chopped');
INSERT INTO base_ingredient (description) VALUES ('Cilantro');
INSERT INTO base_ingredient (description) VALUES ('Cumin, dried');
INSERT INTO base_ingredient (description) VALUES ('Garlic, chopped clove');
INSERT INTO base_ingredient (description) VALUES ('Lemon juice, fresh');
INSERT INTO base_ingredient (description) VALUES ('Lime, cut into wedges');
INSERT INTO base_ingredient (description) VALUES ('Lime juice, fresh');
INSERT INTO base_ingredient (description) VALUES ('Olive oil');
INSERT INTO base_ingredient (description) VALUES ('Onion, green, thinly sliced');
INSERT INTO base_ingredient (description) VALUES ('Onion, red, minced');
INSERT INTO base_ingredient (description) VALUES ('Onion, red, thinly sliced');
INSERT INTO base_ingredient (description) VALUES ('Orange juice, fresh squeezed');
INSERT INTO base_ingredient (description) VALUES ('Orange zest, grated fine');
INSERT INTO base_ingredient (description) VALUES ('Oregano, dried');
INSERT INTO base_ingredient (description) VALUES ('Oregano, fresh');
INSERT INTO base_ingredient (description) VALUES ('Pepper, black, freshly ground');
INSERT INTO base_ingredient (description) VALUES ('Radishes, thinly sliced');
INSERT INTO base_ingredient (description) VALUES ('Salt');
INSERT INTO base_ingredient (description) VALUES ('Salt, Kosher');
INSERT INTO base_ingredient (description) VALUES ('Serrano chiles, stems and seeds removed, minced');
INSERT INTO base_ingredient (description) VALUES ('Sour cream');
INSERT INTO base_ingredient (description) VALUES ('Sour cream, thinned with milk');
INSERT INTO base_ingredient (description) VALUES ('Sugar');
INSERT INTO base_ingredient (description) VALUES ('Tomato, cherry tomatoes, halved');
INSERT INTO base_ingredient (description) VALUES ('Tomato, ripe, seeds and pulp removed, chopped');
INSERT INTO base_ingredient (description) VALUES ('Tortilla, small corn');
